### ISSUE TITLE
NoSuchMethodError when running and building the advisor

### ISSUE THREAD

**Issue by jphillips-bp3** [ODMDev/odm-transformation-advisor#1]
I am attempting to run the advisor against an 8.7 DC, and get the following error:

```
c:\git\odm-transformation-advisor\ota-driver\pkg\ota (master -> origin)
λ run-ota

C:\apache\apache-ant-1.10.7\bin\ant -f ota.xml -inputhandler org.apache.tools.ant.input.SecureInputHandler run-ota
Buildfile: c:\git\odm-transformation-advisor\ota-driver\pkg\ota\ota.xml

run-ota:
Decision Center - Username:
Decision Center - Password:
     [java] Nov 14, 2019 10:33:49 AM ilog.rules.teamserver.client.IlrRemoteSession init
     [java] INFO: Authentication succeeded
     [java] Nov 14, 2019 10:33:50 AM com.ibm.odm.ota.OTARunner run
     [java] INFO: Starting repository analysis for http://localhost:9080/teamserver
     [java] Nov 14, 2019 10:33:50 AM com.ibm.odm.ota.Findings load
     [java] INFO: Loading findings configuration file file:/C:/git/odm-transformation-advisor/ota-driver/pkg/ota/resources/findings.xlsx
     [java] Exception in thread "main" java.lang.NoSuchMethodError: org.apache.poi.ss.usermodel.WorkbookFactory.create(Ljava/io/File;)Lorg/apache/poi/ss/usermodel/Workbook;
     [java]     at com.ibm.odm.ota.Findings.load(Unknown Source)
     [java]     at com.ibm.odm.ota.Findings.getInstance(Unknown Source)
     [java]     at com.ibm.odm.ota.Findings.getParameters(Unknown Source)
     [java]     at com.ibm.odm.ota.checker.Checker.<init>(Unknown Source)
     [java]     at com.ibm.odm.ota.checker.ProjectChecker.<init>(Unknown Source)
     [java]     at com.ibm.odm.ota.OTARunner.run(Unknown Source)
     [java]     at com.ibm.odm.ota.OTARunner.main(Unknown Source)
     [java] Java Result: 1

BUILD SUCCESSFUL
Total time: 7 seconds
```

I have Java 1.8 already installed, so at first I did not attempt to rebuild the OTA Jar files as per the instruction "If you have a Java 1.8 install available, you can readily use the pre-packaged advisor jars to run the application".

So I did try and  rebuild the JAR files but I get the same error. Here are the steps I took and the error message:
```
c:\git\odm-transformation-advisor\ota-xom (master -> origin)
λ ant jar-ota-xom
Buildfile: c:\git\odm-transformation-advisor\ota-xom\build.xml

clean-ota-xom:
   [delete] Deleting directory c:\git\odm-transformation-advisor\ota-xom\bin
   [delete] Deleting directory c:\git\odm-transformation-advisor\ota-xom\build
    [mkdir] Created dir: c:\git\odm-transformation-advisor\ota-xom\bin
    [mkdir] Created dir: c:\git\odm-transformation-advisor\ota-xom\build

compile-ota-xom:
    [javac] Compiling 4 source files to c:\git\odm-transformation-advisor\ota-xom\bin

jar-ota-xom:
      [jar] Building jar: c:\git\odm-transformation-advisor\ota-xom\build\ota-xom.jar

BUILD SUCCESSFUL
Total time: 1 second

c:\git\odm-transformation-advisor\ota-xom (master -> origin)
λ cd ../ota-driver

c:\git\odm-transformation-advisor\ota-driver (master -> origin)
λ ant jar-ota
Buildfile: c:\git\odm-transformation-advisor\ota-driver\build.xml

clean-ota-bin:
   [delete] Deleting directory c:\git\odm-transformation-advisor\ota-driver\bin
    [mkdir] Created dir: c:\git\odm-transformation-advisor\ota-driver\bin

compile-ota:
    [javac] Compiling 17 source files to c:\git\odm-transformation-advisor\ota-driver\bin
    [javac] c:\git\odm-transformation-advisor\ota-driver\src\com\ibm\odm\ota\Findings.java:95: error: no suitable method found for create(File)
    [javac]                     Workbook workbook = WorkbookFactory.create(new File(filepath));
    [javac]                                                        ^
    [javac]     method WorkbookFactory.create(POIFSFileSystem) is not applicable
    [javac]       (argument mismatch; File cannot be converted to POIFSFileSystem)
    [javac]     method WorkbookFactory.create(OPCPackage) is not applicable
    [javac]       (argument mismatch; File cannot be converted to OPCPackage)
    [javac]     method WorkbookFactory.create(InputStream) is not applicable
    [javac]       (argument mismatch; File cannot be converted to InputStream)
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error

BUILD FAILED
c:\git\odm-transformation-advisor\ota-driver\build.xml:34: Compile failed; see the compiler error output for details.

Total time: 1 second
```

You can see that both errors are related to the `WorkbookFactory.create` method.

Here is my Java and Ant details:
```
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
```

```
Apache Ant(TM) version 1.10.7 compiled on September 1 2019
```

**Comment by pberlandier** [comment]
Hi Justin:
Seems like the issue is with the version of Apache POI to manage the config Excel spreadsheet.
I omitted to document this in the prereqs, but POI version 3.10.1 is needed.
It is currently taken from the 8.9 ODM distribution, but if you don't have it, please download 3.10.1 or higher and point to it in the classpath for the `ota-driver` project, instead of the current classpath pointing the ODM POI libs.
Thanks for reporting this!

**Comment by jphillips-bp3** [comment]
@pberlandier Thanks. I will take a look today and let you know how it goes.

**Comment by jphillips-bp3** [comment]
@pberlandier That worked, thanks. I had to put the following JAR's onto the classpath (I added them to the `teamserver/lib` folder of my ODM 8.7 install).
```
poi-3.10.1.jar
poi-ooxml-3.10.1.jar
poi-ooxml-schemas-3.10.1.jar
```
