### ISSUE TITLE
SEVERE: com.ibm.odm.ota.OTAException: Invalid OTA version parameter: v810

### ISSUE THREAD

**Issue by jphillips-bp3** [ODMDev/odm-transformation-advisor#8]
When I run OTA advisor against ODM 8.10.5, I get the following error message:

```C:\Users\Justin Phillips\git\odm-transformation-advisor\ota-driver\pkg\ota>C:\apps\IBM\ODM8105\shared\tools\ant\bin\ant -f ota.xml -inputhandler org.apache.tools.ant.input.SecureInputHandler run-ota
Buildfile: ota.xml

run-ota:
Decision Center - Username:
Decision Center - Password:
     [java] Aug 10, 2021 1:07:23 PM com.ibm.odm.ota.ProjectSelections getSelectedItems
     [java] INFO: @ Processing project list
     [java] Aug 10, 2021 1:07:24 PM com.ibm.odm.ota.OTARunner run
     [java] INFO: Starting repository analysis for http://localhost:9090/teamserver
     [java] Aug 10, 2021 1:07:24 PM com.ibm.odm.ota.Findings load
     [java] INFO: Loading findings configuration file file:/C:/Users/Justin%20Phillips/git/odm-transformation-advisor/ota-driver/pkg/ota/resources/findings.xlsx
     [java] Aug 10, 2021 1:07:25 PM com.ibm.odm.ota.checker.ProjectChecker run
     [java] INFO: @ Checking individual rule projects from repository
     [java] Aug 10, 2021 1:07:25 PM com.ibm.odm.ota.checker.ProjectChecker runOne
     [java] INFO: Checking project LETPension1 in branch [current]
     [java] Cleaning up unclosed ZipFile for archive C:\Users\Justin Phillips\git\odm-transformation-advisor\ota-driver\pkg\ota\resources\findings.xlsx
     [java] Aug 10, 2021 1:07:26 PM com.ibm.odm.ota.checker.Checker handleElementException
     [java] SEVERE: com.ibm.odm.ota.OTAException: Invalid OTA version parameter: v810
     [java]     at com.ibm.odm.ota.DecisionRunner.configureFactory(Unknown Source)
     [java]     at com.ibm.odm.ota.DecisionRunner.<init>(Unknown Source)
     [java]     at com.ibm.odm.ota.checker.ProjectChecker.runRulesetChecks(Unknown Source)
     [java]     at com.ibm.odm.ota.checker.ProjectChecker.runOne(Unknown Source)
     [java]     at com.ibm.odm.ota.checker.ProjectChecker.run(Unknown Source)
     [java]     at com.ibm.odm.ota.OTARunner.run(Unknown Source)
     [java]     at com.ibm.odm.ota.OTARunner.main(Unknown Source)
     [java]
     [java] Aug 10, 2021 1:07:26 PM com.ibm.odm.ota.checker.ProjectGroupChecker run
     [java] INFO: @ Checking project groups or decision services from repository
     [java] Aug 10, 2021 1:07:26 PM com.ibm.odm.ota.checker.Checker handleElementException
     [java] SEVERE: com.ibm.odm.ota.OTAException: Invalid OTA version parameter: v810
     [java]     at com.ibm.odm.ota.DecisionRunner.configureFactory(Unknown Source)
     [java]     at com.ibm.odm.ota.DecisionRunner.<init>(Unknown Source)
     [java]     at com.ibm.odm.ota.checker.ProjectGroupChecker.runOne(Unknown Source)
     [java]     at com.ibm.odm.ota.checker.ProjectGroupChecker.run(Unknown Source)
     [java]     at com.ibm.odm.ota.OTARunner.run(Unknown Source)
     [java]     at com.ibm.odm.ota.OTARunner.main(Unknown Source)
     [java]
     [java] Aug 10, 2021 1:07:26 PM com.ibm.odm.ota.checker.RepositoryChecker run
     [java] INFO: @ Checking repository characteristics
     [java] Aug 10, 2021 1:07:27 PM com.ibm.odm.ota.checker.BOMChecker run
     [java] INFO: @ Checking BOM projects from repository
     [java] Aug 10, 2021 1:07:27 PM com.ibm.odm.ota.checker.BOMChecker checkBOM
     [java] INFO: Checking hefosvarliste BOM from project LETPension1
     [java] Aug 10, 2021 1:07:27 PM com.ibm.odm.ota.checker.BOMChecker checkBOM
     [java] INFO: Checking helper BOM from project LETPension1
     [java] Aug 10, 2021 1:07:27 PM com.ibm.odm.ota.checker.BOMChecker checkBOM
     [java] INFO: Checking jdk BOM from project LETPension1
     [java] Aug 10, 2021 1:07:27 PM com.ibm.odm.ota.checker.BOMChecker checkBOM
     [java] INFO: Checking jrules-engine BOM from project LETPension1
     [java] Aug 10, 2021 1:07:27 PM com.ibm.odm.ota.checker.BOMChecker checkBOM
     [java] INFO: Checking letmodel BOM from project LETPension1
     [java] Aug 10, 2021 1:07:27 PM com.ibm.odm.ota.checker.BOMChecker checkBOM
     [java] INFO: Checking result BOM from project LETPension1
     [java] Aug 10, 2021 1:07:27 PM com.ibm.odm.ota.checker.BOMChecker checkB2X
     [java] INFO: Checking hefosvarliste B2X from project LETPension1
     [java] Aug 10, 2021 1:07:27 PM com.ibm.odm.ota.checker.BOMChecker checkB2X
     [java] INFO: Checking helper B2X from project LETPension1
     [java] Aug 10, 2021 1:07:27 PM com.ibm.odm.ota.checker.BOMChecker checkB2X
     [java] INFO: Checking jdk B2X from project LETPension1
     [java] Aug 10, 2021 1:07:27 PM com.ibm.odm.ota.checker.BOMChecker checkB2X
     [java] INFO: Checking jrules-engine B2X from project LETPension1
     [java] Aug 10, 2021 1:07:27 PM com.ibm.odm.ota.checker.BOMChecker checkB2X
     [java] INFO: Checking letmodel B2X from project LETPension1
     [java] Aug 10, 2021 1:07:27 PM com.ibm.odm.ota.checker.BOMChecker checkB2X
     [java] INFO: Checking result B2X from project LETPension1
     [java] Aug 10, 2021 1:07:27 PM com.ibm.odm.ota.checker.BOMChecker checkVoc
     [java] INFO: Checking hefosvarliste vocabulary from project LETPension1
     [java] Aug 10, 2021 1:07:27 PM com.ibm.odm.ota.checker.VOCSpeller <init>
     [java] WARNING: Cannot find the spelling dictionary file 'spelling.txt' in the resources folder. Spell check will not be performed.
     [java] Aug 10, 2021 1:07:27 PM com.ibm.odm.ota.checker.BOMChecker checkVoc
     [java] INFO: Checking helper vocabulary from project LETPension1
     [java] Aug 10, 2021 1:07:27 PM com.ibm.odm.ota.checker.BOMChecker checkVoc
     [java] INFO: Checking jdk vocabulary from project LETPension1
     [java] Aug 10, 2021 1:07:27 PM com.ibm.odm.ota.checker.BOMChecker checkVoc
     [java] INFO: Checking jrules-engine vocabulary from project LETPension1
     [java] Aug 10, 2021 1:07:27 PM com.ibm.odm.ota.checker.BOMChecker checkVoc
     [java] INFO: Checking letmodel vocabulary from project LETPension1
     [java] Aug 10, 2021 1:07:27 PM com.ibm.odm.ota.checker.BOMChecker checkVoc
     [java] INFO: Checking result vocabulary from project LETPension1
     [java] Aug 10, 2021 1:07:28 PM com.ibm.odm.ota.OTARunner run
     [java] INFO: Analysis completed, results available in ota-report.html
     [java] Aug 10, 2021 1:07:28 PM com.ibm.odm.ota.DCConnection endSession
     [java] INFO: Ending use of DC session

BUILD SUCCESSFUL
Total time: 14 seconds
C:\Users\Justin Phillips\git\odm-transformation-advisor\ota-driver\pkg\ota>
```

Below is my `ota.properties` file:

```
ota.url=http://localhost:9090/teamserver
ota.datasource=
ota.projects=LETPension1
ota.report=ota-report.html
ota.version=v810
odm.dir=C:/apps/IBM/ODM8105
```

Could you advise on what the problem might be, as the `ota.version` parameter looks correct, thanks.

**Comment by alainrobert** [comment]
project has been updated
